[project]
name = "bp-ecg-preprocessing-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "pillow>=10.4.0",
    "pymupdf>=1.25.3",
    "tqdm>=4.67.1",
]
